// constellation.js  -  Generated by a program written by Don Cross  -  http://cosinekitty.com/

var ConstellationEdgeArray = [
    { 'ConciseName':'الدب الأصغر', 'DecBottom': 88.0000, 'RaLeft':  0.0000, 'RaRight': 24.0000 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 86.5000, 'RaLeft':  8.0000, 'RaRight': 14.5000 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 86.1667, 'RaLeft': 21.0000, 'RaRight': 23.0000 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 86.0000, 'RaLeft': 18.0000, 'RaRight': 21.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 85.0000, 'RaLeft':  0.0000, 'RaRight':  8.0000 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 82.0000, 'RaLeft':  9.1667, 'RaRight': 10.6667 }
  , { 'ConciseName':'Cep', 'DecBottom': 80.0000, 'RaLeft':  0.0000, 'RaRight':  5.0000 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 80.0000, 'RaLeft': 10.6667, 'RaRight': 14.5000 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 80.0000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'التنين', 'DecBottom': 80.0000, 'RaLeft': 20.1667, 'RaRight': 21.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 77.0000, 'RaLeft':  0.0000, 'RaRight':  3.5083 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 77.0000, 'RaLeft': 11.5000, 'RaRight': 13.5833 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 75.0000, 'RaLeft': 16.5333, 'RaRight': 17.5000 }
  , { 'ConciseName':'Cep', 'DecBottom': 75.0000, 'RaLeft': 20.1667, 'RaRight': 20.6667 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 73.5000, 'RaLeft':  7.9667, 'RaRight':  9.1667 }
  , { 'ConciseName':'التنين', 'DecBottom': 73.5000, 'RaLeft':  9.1667, 'RaRight': 11.3333 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 70.0000, 'RaLeft': 13.0000, 'RaRight': 16.5333 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 68.0000, 'RaLeft':  3.1000, 'RaRight':  3.4167 }
  , { 'ConciseName':'التنين', 'DecBottom': 67.0000, 'RaLeft': 20.4167, 'RaRight': 20.6667 }
  , { 'ConciseName':'التنين', 'DecBottom': 66.5000, 'RaLeft': 11.3333, 'RaRight': 12.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 66.0000, 'RaLeft':  0.0000, 'RaRight':  0.3333 }
  , { 'ConciseName':'الدب الأصغر', 'DecBottom': 66.0000, 'RaLeft': 14.0000, 'RaRight': 15.6667 }
  , { 'ConciseName':'Cep', 'DecBottom': 66.0000, 'RaLeft': 23.5833, 'RaRight': 24.0000 }
  , { 'ConciseName':'التنين', 'DecBottom': 64.0000, 'RaLeft': 12.0000, 'RaRight': 13.5000 }
  , { 'ConciseName':'التنين', 'DecBottom': 63.0000, 'RaLeft': 13.5000, 'RaRight': 14.4167 }
  , { 'ConciseName':'Cep', 'DecBottom': 63.0000, 'RaLeft': 23.1667, 'RaRight': 23.5833 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 62.0000, 'RaLeft':  6.1000, 'RaRight':  7.0000 }
  , { 'ConciseName':'التنين', 'DecBottom': 61.5000, 'RaLeft': 20.0000, 'RaRight': 20.4167 }
  , { 'ConciseName':'Cep', 'DecBottom': 60.9167, 'RaLeft': 20.5367, 'RaRight': 20.6000 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 60.0000, 'RaLeft':  7.0000, 'RaRight':  7.9667 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 60.0000, 'RaLeft':  7.9667, 'RaRight':  8.4167 }
  , { 'ConciseName':'التنين', 'DecBottom': 59.5000, 'RaLeft': 19.7667, 'RaRight': 20.0000 }
  , { 'ConciseName':'Cep', 'DecBottom': 59.5000, 'RaLeft': 20.0000, 'RaRight': 20.5367 }
  , { 'ConciseName':'Cep', 'DecBottom': 59.0833, 'RaLeft': 22.8667, 'RaRight': 23.1667 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 58.5000, 'RaLeft':  0.0000, 'RaRight':  2.4333 }
  , { 'ConciseName':'التنين', 'DecBottom': 58.0000, 'RaLeft': 19.4167, 'RaRight': 19.7667 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 57.5000, 'RaLeft':  1.7000, 'RaRight':  1.9083 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 57.0000, 'RaLeft':  2.4333, 'RaRight':  3.1000 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 57.0000, 'RaLeft':  3.1000, 'RaRight':  3.1667 }
  , { 'ConciseName':'Cep', 'DecBottom': 56.2500, 'RaLeft': 22.3167, 'RaRight': 22.8667 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 56.0000, 'RaLeft':  5.0000, 'RaRight':  6.1000 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 55.5000, 'RaLeft': 14.0333, 'RaRight': 14.4167 }
  , { 'ConciseName':'التنين', 'DecBottom': 55.5000, 'RaLeft': 14.4167, 'RaRight': 19.4167 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 55.0000, 'RaLeft':  3.1667, 'RaRight':  3.3333 }
  , { 'ConciseName':'Cep', 'DecBottom': 55.0000, 'RaLeft': 22.1333, 'RaRight': 22.3167 }
  , { 'ConciseName':'Cep', 'DecBottom': 54.8333, 'RaLeft': 20.6000, 'RaRight': 21.9667 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 54.0000, 'RaLeft':  0.0000, 'RaRight':  1.7000 }
  , { 'ConciseName':'الوشق', 'DecBottom': 54.0000, 'RaLeft':  6.1000, 'RaRight':  6.5000 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 53.0000, 'RaLeft': 12.0833, 'RaRight': 13.5000 }
  , { 'ConciseName':'التنين', 'DecBottom': 53.0000, 'RaLeft': 15.2500, 'RaRight': 15.7500 }
  , { 'ConciseName':'Cep', 'DecBottom': 52.7500, 'RaLeft': 21.9667, 'RaRight': 22.1333 }
  , { 'ConciseName':'الزرافة', 'DecBottom': 52.5000, 'RaLeft':  3.3333, 'RaRight':  5.0000 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 52.5000, 'RaLeft': 22.8667, 'RaRight': 23.3333 }
  , { 'ConciseName':'التنين', 'DecBottom': 51.5000, 'RaLeft': 15.7500, 'RaRight': 17.0000 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 50.5000, 'RaLeft':  2.0417, 'RaRight':  2.5167 }
  , { 'ConciseName':'التنين', 'DecBottom': 50.5000, 'RaLeft': 17.0000, 'RaRight': 18.2333 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 50.0000, 'RaLeft':  0.0000, 'RaRight':  1.3667 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 50.0000, 'RaLeft':  1.3667, 'RaRight':  1.6667 }
  , { 'ConciseName':'الوشق', 'DecBottom': 50.0000, 'RaLeft':  6.5000, 'RaRight':  6.8000 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 50.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 48.5000, 'RaLeft': 13.5000, 'RaRight': 14.0333 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 48.0000, 'RaLeft':  0.0000, 'RaRight':  1.1167 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 48.0000, 'RaLeft': 23.5833, 'RaRight': 24.0000 }
  , { 'ConciseName':'هرقل', 'DecBottom': 47.5000, 'RaLeft': 18.1750, 'RaRight': 18.2333 }
  , { 'ConciseName':'التنين', 'DecBottom': 47.5000, 'RaLeft': 18.2333, 'RaRight': 19.0833 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 47.5000, 'RaLeft': 19.0833, 'RaRight': 19.1667 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 47.0000, 'RaLeft':  1.6667, 'RaRight':  2.0417 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 47.0000, 'RaLeft':  8.4167, 'RaRight':  9.1667 }
  , { 'ConciseName':'ذات الكرسي', 'DecBottom': 46.0000, 'RaLeft':  0.1667, 'RaRight':  0.8667 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 45.0000, 'RaLeft': 12.0000, 'RaRight': 12.0833 }
  , { 'ConciseName':'الوشق', 'DecBottom': 44.5000, 'RaLeft':  6.8000, 'RaRight':  7.3667 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 44.0000, 'RaLeft': 21.9083, 'RaRight': 21.9667 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 43.7500, 'RaLeft': 21.8750, 'RaRight': 21.9083 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 43.5000, 'RaLeft': 19.1667, 'RaRight': 19.4000 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 42.0000, 'RaLeft':  9.1667, 'RaRight': 10.1667 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 40.0000, 'RaLeft': 10.1667, 'RaRight': 10.7833 }
  , { 'ConciseName':'العواء', 'DecBottom': 40.0000, 'RaLeft': 15.4333, 'RaRight': 15.7500 }
  , { 'ConciseName':'هرقل', 'DecBottom': 40.0000, 'RaLeft': 15.7500, 'RaRight': 16.3333 }
  , { 'ConciseName':'الوشق', 'DecBottom': 39.7500, 'RaLeft':  9.2500, 'RaRight':  9.5833 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 36.7500, 'RaLeft':  0.0000, 'RaRight':  2.5167 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 36.7500, 'RaLeft':  2.5167, 'RaRight':  2.5667 }
  , { 'ConciseName':'القيثارة', 'DecBottom': 36.5000, 'RaLeft': 19.3583, 'RaRight': 19.4000 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 36.0000, 'RaLeft':  4.5000, 'RaRight':  4.6917 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 36.0000, 'RaLeft': 21.7333, 'RaRight': 21.8750 }
  , { 'ConciseName':'العظاءة', 'DecBottom': 36.0000, 'RaLeft': 21.8750, 'RaRight': 22.0000 }
  , { 'ConciseName':'ممسك الأعنة', 'DecBottom': 35.5000, 'RaLeft':  6.5333, 'RaRight':  7.3667 }
  , { 'ConciseName':'الوشق', 'DecBottom': 35.5000, 'RaLeft':  7.3667, 'RaRight':  7.7500 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 35.0000, 'RaLeft':  0.0000, 'RaRight':  2.0000 }
  , { 'ConciseName':'العظاءة', 'DecBottom': 35.0000, 'RaLeft': 22.0000, 'RaRight': 22.8167 }
  , { 'ConciseName':'العظاءة', 'DecBottom': 34.5000, 'RaLeft': 22.8167, 'RaRight': 22.8667 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 34.5000, 'RaLeft': 22.8667, 'RaRight': 23.5000 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 34.0000, 'RaLeft':  2.5667, 'RaRight':  2.7167 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 34.0000, 'RaLeft': 10.7833, 'RaRight': 11.0000 }
  , { 'ConciseName':'CVn', 'DecBottom': 34.0000, 'RaLeft': 12.0000, 'RaRight': 12.3333 }
  , { 'ConciseName':'الوشق', 'DecBottom': 33.5000, 'RaLeft':  7.7500, 'RaRight':  9.2500 }
  , { 'ConciseName':'الأسد الأصغر', 'DecBottom': 33.5000, 'RaLeft':  9.2500, 'RaRight':  9.8833 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 33.0000, 'RaLeft':  0.7167, 'RaRight':  1.4083 }
  , { 'ConciseName':'العواء', 'DecBottom': 33.0000, 'RaLeft': 15.1833, 'RaRight': 15.4333 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 32.0833, 'RaLeft': 23.5000, 'RaRight': 23.7500 }
  , { 'ConciseName':'CVn', 'DecBottom': 32.0000, 'RaLeft': 12.3333, 'RaRight': 13.2500 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 31.3333, 'RaLeft': 23.7500, 'RaRight': 24.0000 }
  , { 'ConciseName':'CVn', 'DecBottom': 30.7500, 'RaLeft': 13.9583, 'RaRight': 14.0333 }
  , { 'ConciseName':'المثلث', 'DecBottom': 30.6667, 'RaLeft':  2.4167, 'RaRight':  2.7167 }
  , { 'ConciseName':'برشاوس', 'DecBottom': 30.6667, 'RaLeft':  2.7167, 'RaRight':  4.5000 }
  , { 'ConciseName':'ممسك الأعنة', 'DecBottom': 30.0000, 'RaLeft':  4.5000, 'RaRight':  4.7500 }
  , { 'ConciseName':'القيثارة', 'DecBottom': 30.0000, 'RaLeft': 18.1750, 'RaRight': 19.3583 }
  , { 'ConciseName':'الدب الأكبر', 'DecBottom': 29.0000, 'RaLeft': 11.0000, 'RaRight': 12.0000 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 29.0000, 'RaLeft': 19.6667, 'RaRight': 20.9167 }
  , { 'ConciseName':'ممسك الأعنة', 'DecBottom': 28.5000, 'RaLeft':  4.7500, 'RaRight':  5.8833 }
  , { 'ConciseName':'الأسد الأصغر', 'DecBottom': 28.5000, 'RaLeft':  9.8833, 'RaRight': 10.5000 }
  , { 'ConciseName':'CVn', 'DecBottom': 28.5000, 'RaLeft': 13.2500, 'RaRight': 13.9583 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 28.0000, 'RaLeft':  0.0000, 'RaRight':  0.0667 }
  , { 'ConciseName':'المثلث', 'DecBottom': 28.0000, 'RaLeft':  1.4083, 'RaRight':  1.6667 }
  , { 'ConciseName':'ممسك الأعنة', 'DecBottom': 28.0000, 'RaLeft':  5.8833, 'RaRight':  6.5333 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 28.0000, 'RaLeft':  7.8833, 'RaRight':  8.0000 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 28.0000, 'RaLeft': 20.9167, 'RaRight': 21.7333 }
  , { 'ConciseName':'الدجاجة', 'DecBottom': 27.5000, 'RaLeft': 19.2583, 'RaRight': 19.6667 }
  , { 'ConciseName':'المثلث', 'DecBottom': 27.2500, 'RaLeft':  1.9167, 'RaRight':  2.4167 }
  , { 'ConciseName':'الإكليل الشمالي', 'DecBottom': 27.0000, 'RaLeft': 16.1667, 'RaRight': 16.3333 }
  , { 'ConciseName':'العواء', 'DecBottom': 26.0000, 'RaLeft': 15.0833, 'RaRight': 15.1833 }
  , { 'ConciseName':'الإكليل الشمالي', 'DecBottom': 26.0000, 'RaLeft': 15.1833, 'RaRight': 16.1667 }
  , { 'ConciseName':'القيثارة', 'DecBottom': 26.0000, 'RaLeft': 18.3667, 'RaRight': 18.8667 }
  , { 'ConciseName':'الأسد الأصغر', 'DecBottom': 25.5000, 'RaLeft': 10.7500, 'RaRight': 11.0000 }
  , { 'ConciseName':'القيثارة', 'DecBottom': 25.5000, 'RaLeft': 18.8667, 'RaRight': 19.2583 }
  , { 'ConciseName':'المثلث', 'DecBottom': 25.0000, 'RaLeft':  1.6667, 'RaRight':  1.9167 }
  , { 'ConciseName':'الحوت', 'DecBottom': 23.7500, 'RaLeft':  0.7167, 'RaRight':  0.8500 }
  , { 'ConciseName':'الأسد الأصغر', 'DecBottom': 23.5000, 'RaLeft': 10.5000, 'RaRight': 10.7500 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 23.5000, 'RaLeft': 21.2500, 'RaRight': 21.4167 }
  , { 'ConciseName':'الثور', 'DecBottom': 22.8333, 'RaLeft':  5.7000, 'RaRight':  5.8833 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 22.0000, 'RaLeft':  0.0667, 'RaRight':  0.1417 }
  , { 'ConciseName':'الحية', 'DecBottom': 22.0000, 'RaLeft': 15.9167, 'RaRight': 16.0333 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 21.5000, 'RaLeft':  5.8833, 'RaRight':  6.2167 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 21.2500, 'RaLeft': 19.8333, 'RaRight': 20.2500 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 21.0833, 'RaLeft': 18.8667, 'RaRight': 19.2500 }
  , { 'ConciseName':'أندروميدا', 'DecBottom': 21.0000, 'RaLeft':  0.1417, 'RaRight':  0.8500 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 20.5000, 'RaLeft': 20.2500, 'RaRight': 20.5667 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 20.0000, 'RaLeft':  7.8083, 'RaRight':  7.8833 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 19.5000, 'RaLeft': 20.5667, 'RaRight': 21.2500 }
  , { 'ConciseName':'الثعلب', 'DecBottom': 19.1667, 'RaLeft': 19.2500, 'RaRight': 19.8333 }
  , { 'ConciseName':'الحمل', 'DecBottom': 19.0000, 'RaLeft':  3.2833, 'RaRight':  3.3667 }
  , { 'ConciseName':'السهم', 'DecBottom': 18.5000, 'RaLeft': 18.8667, 'RaRight': 19.0000 }
  , { 'ConciseName':'الجبار', 'DecBottom': 18.0000, 'RaLeft':  5.7000, 'RaRight':  5.7667 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 17.5000, 'RaLeft':  6.2167, 'RaRight':  6.3083 }
  , { 'ConciseName':'السهم', 'DecBottom': 16.1667, 'RaLeft': 19.0000, 'RaRight': 19.8333 }
  , { 'ConciseName':'الثور', 'DecBottom': 16.0000, 'RaLeft':  4.9667, 'RaRight':  5.3333 }
  , { 'ConciseName':'هرقل', 'DecBottom': 16.0000, 'RaLeft': 15.9167, 'RaRight': 16.0833 }
  , { 'ConciseName':'السهم', 'DecBottom': 15.7500, 'RaLeft': 19.8333, 'RaRight': 20.2500 }
  , { 'ConciseName':'الثور', 'DecBottom': 15.5000, 'RaLeft':  4.6167, 'RaRight':  4.9667 }
  , { 'ConciseName':'الثور', 'DecBottom': 15.5000, 'RaLeft':  5.3333, 'RaRight':  5.6000 }
  , { 'ConciseName':'الضفيرة', 'DecBottom': 15.0000, 'RaLeft': 12.8333, 'RaRight': 13.5000 }
  , { 'ConciseName':'هرقل', 'DecBottom': 14.3333, 'RaLeft': 17.2500, 'RaRight': 18.2500 }
  , { 'ConciseName':'الضفيرة', 'DecBottom': 14.0000, 'RaLeft': 11.8667, 'RaRight': 12.8333 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 13.5000, 'RaLeft':  7.5000, 'RaRight':  7.8083 }
  , { 'ConciseName':'هرقل', 'DecBottom': 12.8333, 'RaLeft': 16.7500, 'RaRight': 17.2500 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom': 12.5000, 'RaLeft':  0.0000, 'RaRight':  0.1417 }
  , { 'ConciseName':'الثور', 'DecBottom': 12.5000, 'RaLeft':  5.6000, 'RaRight':  5.7667 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 12.5000, 'RaLeft':  7.0000, 'RaRight':  7.5000 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom': 12.5000, 'RaLeft': 21.1167, 'RaRight': 21.3333 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 12.0000, 'RaLeft':  6.3083, 'RaRight':  6.9333 }
  , { 'ConciseName':'هرقل', 'DecBottom': 12.0000, 'RaLeft': 18.2500, 'RaRight': 18.8667 }
  , { 'ConciseName':'الدلفين', 'DecBottom': 11.8333, 'RaLeft': 20.8750, 'RaRight': 21.0500 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom': 11.8333, 'RaLeft': 21.0500, 'RaRight': 21.1167 }
  , { 'ConciseName':'الأسد', 'DecBottom': 11.0000, 'RaLeft': 11.5167, 'RaRight': 11.8667 }
  , { 'ConciseName':'الجبار', 'DecBottom': 10.0000, 'RaLeft':  6.2417, 'RaRight':  6.3083 }
  , { 'ConciseName':'التوأمين', 'DecBottom': 10.0000, 'RaLeft':  6.9333, 'RaRight':  7.0000 }
  , { 'ConciseName':'السرطان', 'DecBottom': 10.0000, 'RaLeft':  7.8083, 'RaRight':  7.9250 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom': 10.0000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'الحمل', 'DecBottom':  9.9167, 'RaLeft':  1.6667, 'RaRight':  3.2833 }
  , { 'ConciseName':'الدلفين', 'DecBottom':  8.5000, 'RaLeft': 20.1417, 'RaRight': 20.3000 }
  , { 'ConciseName':'العواء', 'DecBottom':  8.0000, 'RaLeft': 13.5000, 'RaRight': 15.0833 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom':  7.5000, 'RaLeft': 22.7500, 'RaRight': 23.8333 }
  , { 'ConciseName':'السرطان', 'DecBottom':  7.0000, 'RaLeft':  7.9250, 'RaRight':  9.2500 }
  , { 'ConciseName':'الأسد', 'DecBottom':  7.0000, 'RaLeft':  9.2500, 'RaRight': 10.7500 }
  , { 'ConciseName':'الحواء', 'DecBottom':  6.2500, 'RaLeft': 18.2500, 'RaRight': 18.6622 }
  , { 'ConciseName':'العقاب', 'DecBottom':  6.2500, 'RaLeft': 18.6622, 'RaRight': 18.8667 }
  , { 'ConciseName':'الدلفين', 'DecBottom':  6.0000, 'RaLeft': 20.8333, 'RaRight': 20.8750 }
  , { 'ConciseName':'الكلب الأصغر', 'DecBottom':  5.5000, 'RaLeft':  7.0000, 'RaRight':  7.0167 }
  , { 'ConciseName':'الحية', 'DecBottom':  4.5000, 'RaLeft': 18.2500, 'RaRight': 18.4250 }
  , { 'ConciseName':'هرقل', 'DecBottom':  4.0000, 'RaLeft': 16.0833, 'RaRight': 16.7500 }
  , { 'ConciseName':'الحواء', 'DecBottom':  3.0000, 'RaLeft': 18.2500, 'RaRight': 18.4250 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom':  2.7500, 'RaLeft': 21.4667, 'RaRight': 21.6667 }
  , { 'ConciseName':'الحوت', 'DecBottom':  2.0000, 'RaLeft':  0.0000, 'RaRight':  2.0000 }
  , { 'ConciseName':'الحية', 'DecBottom':  2.0000, 'RaLeft': 18.5833, 'RaRight': 18.8667 }
  , { 'ConciseName':'الدلفين', 'DecBottom':  2.0000, 'RaLeft': 20.3000, 'RaRight': 20.8333 }
  , { 'ConciseName':'قطعة الفرس', 'DecBottom':  2.0000, 'RaLeft': 20.8333, 'RaRight': 21.3333 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom':  2.0000, 'RaLeft': 21.3333, 'RaRight': 21.4667 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom':  2.0000, 'RaLeft': 22.0000, 'RaRight': 22.7500 }
  , { 'ConciseName':'الفرس المجنح', 'DecBottom':  1.7500, 'RaLeft': 21.6667, 'RaRight': 22.0000 }
  , { 'ConciseName':'الكلب الأصغر', 'DecBottom':  1.5000, 'RaLeft':  7.0167, 'RaRight':  7.2000 }
  , { 'ConciseName':'الثور', 'DecBottom':  0.0000, 'RaLeft':  3.5833, 'RaRight':  4.6167 }
  , { 'ConciseName':'الجبار', 'DecBottom':  0.0000, 'RaLeft':  4.6167, 'RaRight':  4.6667 }
  , { 'ConciseName':'الكلب الأصغر', 'DecBottom':  0.0000, 'RaLeft':  7.2000, 'RaRight':  8.0833 }
  , { 'ConciseName':'العذراء', 'DecBottom':  0.0000, 'RaLeft': 14.6667, 'RaRight': 15.0833 }
  , { 'ConciseName':'الحواء', 'DecBottom':  0.0000, 'RaLeft': 17.8333, 'RaRight': 18.2500 }
  , { 'ConciseName':'قيطس', 'DecBottom': -1.7500, 'RaLeft':  2.6500, 'RaRight':  3.2833 }
  , { 'ConciseName':'الثور', 'DecBottom': -1.7500, 'RaLeft':  3.2833, 'RaRight':  3.5833 }
  , { 'ConciseName':'الحية', 'DecBottom': -3.2500, 'RaLeft': 15.0833, 'RaRight': 16.2667 }
  , { 'ConciseName':'الجبار', 'DecBottom': -4.0000, 'RaLeft':  4.6667, 'RaRight':  5.0833 }
  , { 'ConciseName':'الجبار', 'DecBottom': -4.0000, 'RaLeft':  5.8333, 'RaRight':  6.2417 }
  , { 'ConciseName':'الحية', 'DecBottom': -4.0000, 'RaLeft': 17.8333, 'RaRight': 17.9667 }
  , { 'ConciseName':'الحية', 'DecBottom': -4.0000, 'RaLeft': 18.2500, 'RaRight': 18.5833 }
  , { 'ConciseName':'العقاب', 'DecBottom': -4.0000, 'RaLeft': 18.5833, 'RaRight': 18.8667 }
  , { 'ConciseName':'الحوت', 'DecBottom': -4.0000, 'RaLeft': 22.7500, 'RaRight': 23.8333 }
  , { 'ConciseName':'الأسد', 'DecBottom': -6.0000, 'RaLeft': 10.7500, 'RaRight': 11.5167 }
  , { 'ConciseName':'العذراء', 'DecBottom': -6.0000, 'RaLeft': 11.5167, 'RaRight': 11.8333 }
  , { 'ConciseName':'الحوت', 'DecBottom': -7.0000, 'RaLeft':  0.0000, 'RaRight':  0.3333 }
  , { 'ConciseName':'الحوت', 'DecBottom': -7.0000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'العذراء', 'DecBottom': -8.0000, 'RaLeft': 14.2500, 'RaRight': 14.6667 }
  , { 'ConciseName':'الحواء', 'DecBottom': -8.0000, 'RaLeft': 15.9167, 'RaRight': 16.2667 }
  , { 'ConciseName':'العقاب', 'DecBottom': -9.0000, 'RaLeft': 20.0000, 'RaRight': 20.5333 }
  , { 'ConciseName':'الدلو', 'DecBottom': -9.0000, 'RaLeft': 21.3333, 'RaRight': 21.8667 }
  , { 'ConciseName':'الحواء', 'DecBottom':-10.0000, 'RaLeft': 17.1667, 'RaRight': 17.9667 }
  , { 'ConciseName':'وحيد القرن', 'DecBottom':-11.0000, 'RaLeft':  5.8333, 'RaRight':  8.0833 }
  , { 'ConciseName':'النهر', 'DecBottom':-11.0000, 'RaLeft':  4.9167, 'RaRight':  5.0833 }
  , { 'ConciseName':'الجبار', 'DecBottom':-11.0000, 'RaLeft':  5.0833, 'RaRight':  5.8333 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-11.0000, 'RaLeft':  8.0833, 'RaRight':  8.3667 }
  , { 'ConciseName':'آلة السدس', 'DecBottom':-11.0000, 'RaLeft':  9.5833, 'RaRight': 10.7500 }
  , { 'ConciseName':'العذراء', 'DecBottom':-11.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'الحواء', 'DecBottom':-11.6667, 'RaLeft': 17.5833, 'RaRight': 17.6667 }
  , { 'ConciseName':'العقاب', 'DecBottom':-12.0333, 'RaLeft': 18.8667, 'RaRight': 20.0000 }
  , { 'ConciseName':'النهر', 'DecBottom':-14.5000, 'RaLeft':  4.8333, 'RaRight':  4.9167 }
  , { 'ConciseName':'الدلو', 'DecBottom':-15.0000, 'RaLeft': 20.5333, 'RaRight': 21.3333 }
  , { 'ConciseName':'الحية', 'DecBottom':-16.0000, 'RaLeft': 17.1667, 'RaRight': 18.2500 }
  , { 'ConciseName':'الترس', 'DecBottom':-16.0000, 'RaLeft': 18.2500, 'RaRight': 18.8667 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-17.0000, 'RaLeft':  8.3667, 'RaRight':  8.5833 }
  , { 'ConciseName':'الحواء', 'DecBottom':-18.2500, 'RaLeft': 16.2667, 'RaRight': 16.3750 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-19.0000, 'RaLeft':  8.5833, 'RaRight':  9.0833 }
  , { 'ConciseName':'الباطية', 'DecBottom':-19.0000, 'RaLeft': 10.7500, 'RaRight': 10.8333 }
  , { 'ConciseName':'العقرب', 'DecBottom':-19.2500, 'RaLeft': 16.2667, 'RaRight': 16.3750 }
  , { 'ConciseName':'الميزان', 'DecBottom':-20.0000, 'RaLeft': 15.6667, 'RaRight': 15.9167 }
  , { 'ConciseName':'الغراب', 'DecBottom':-22.0000, 'RaLeft': 12.5833, 'RaRight': 12.8333 }
  , { 'ConciseName':'العذراء', 'DecBottom':-22.0000, 'RaLeft': 12.8333, 'RaRight': 14.2500 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-24.0000, 'RaLeft':  9.0833, 'RaRight':  9.7500 }
  , { 'ConciseName':'قيطس', 'DecBottom':-24.3833, 'RaLeft':  1.6667, 'RaRight':  2.6500 }
  , { 'ConciseName':'النهر', 'DecBottom':-24.3833, 'RaLeft':  2.6500, 'RaRight':  3.7500 }
  , { 'ConciseName':'الباطية', 'DecBottom':-24.5000, 'RaLeft': 10.8333, 'RaRight': 11.8333 }
  , { 'ConciseName':'الغراب', 'DecBottom':-24.5000, 'RaLeft': 11.8333, 'RaRight': 12.5833 }
  , { 'ConciseName':'الميزان', 'DecBottom':-24.5000, 'RaLeft': 14.2500, 'RaRight': 14.9167 }
  , { 'ConciseName':'الحواء', 'DecBottom':-24.5833, 'RaLeft': 16.2667, 'RaRight': 16.7500 }
  , { 'ConciseName':'قيطس', 'DecBottom':-25.5000, 'RaLeft':  0.0000, 'RaRight':  1.6667 }
  , { 'ConciseName':'الجدي', 'DecBottom':-25.5000, 'RaLeft': 21.3333, 'RaRight': 21.8667 }
  , { 'ConciseName':'الدلو', 'DecBottom':-25.5000, 'RaLeft': 21.8667, 'RaRight': 23.8333 }
  , { 'ConciseName':'قيطس', 'DecBottom':-25.5000, 'RaLeft': 23.8333, 'RaRight': 24.0000 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-26.5000, 'RaLeft':  9.7500, 'RaRight': 10.2500 }
  , { 'ConciseName':'النهر', 'DecBottom':-27.2500, 'RaLeft':  4.7000, 'RaRight':  4.8333 }
  , { 'ConciseName':'الأرنب', 'DecBottom':-27.2500, 'RaLeft':  4.8333, 'RaRight':  6.1167 }
  , { 'ConciseName':'الجدي', 'DecBottom':-28.0000, 'RaLeft': 20.0000, 'RaRight': 21.3333 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-29.1667, 'RaLeft': 10.2500, 'RaRight': 10.5833 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-29.5000, 'RaLeft': 12.5833, 'RaRight': 14.9167 }
  , { 'ConciseName':'الميزان', 'DecBottom':-29.5000, 'RaLeft': 14.9167, 'RaRight': 15.6667 }
  , { 'ConciseName':'العقرب', 'DecBottom':-29.5000, 'RaLeft': 15.6667, 'RaRight': 16.0000 }
  , { 'ConciseName':'النهر', 'DecBottom':-30.0000, 'RaLeft':  4.5833, 'RaRight':  4.7000 }
  , { 'ConciseName':'الحواء', 'DecBottom':-30.0000, 'RaLeft': 16.7500, 'RaRight': 17.6000 }
  , { 'ConciseName':'القوس', 'DecBottom':-30.0000, 'RaLeft': 17.6000, 'RaRight': 17.8333 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-31.1667, 'RaLeft': 10.5833, 'RaRight': 10.8333 }
  , { 'ConciseName':'الكلب الأكبر', 'DecBottom':-33.0000, 'RaLeft':  6.1167, 'RaRight':  7.3667 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-33.0000, 'RaLeft': 12.2500, 'RaRight': 12.5833 }
  , { 'ConciseName':'الشجاع', 'DecBottom':-35.0000, 'RaLeft': 10.8333, 'RaRight': 12.2500 }
  , { 'ConciseName':'الكور', 'DecBottom':-36.0000, 'RaLeft':  3.5000, 'RaRight':  3.7500 }
  , { 'ConciseName':'بيت الإبرة', 'DecBottom':-36.7500, 'RaLeft':  8.3667, 'RaRight':  9.3667 }
  , { 'ConciseName':'النهر', 'DecBottom':-37.0000, 'RaLeft':  4.2667, 'RaRight':  4.5833 }
  , { 'ConciseName':'القوس', 'DecBottom':-37.0000, 'RaLeft': 17.8333, 'RaRight': 19.1667 }
  , { 'ConciseName':'الحوت الجنوبي', 'DecBottom':-37.0000, 'RaLeft': 21.3333, 'RaRight': 23.0000 }
  , { 'ConciseName':'معمل النحات', 'DecBottom':-37.0000, 'RaLeft': 23.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'الكور', 'DecBottom':-39.5833, 'RaLeft':  3.0000, 'RaRight':  3.5000 }
  , { 'ConciseName':'مفرغة الهواء', 'DecBottom':-39.7500, 'RaLeft':  9.3667, 'RaRight': 11.0000 }
  , { 'ConciseName':'معمل النحات', 'DecBottom':-40.0000, 'RaLeft':  0.0000, 'RaRight':  1.6667 }
  , { 'ConciseName':'الكور', 'DecBottom':-40.0000, 'RaLeft':  1.6667, 'RaRight':  3.0000 }
  , { 'ConciseName':'النهر', 'DecBottom':-40.0000, 'RaLeft':  3.8667, 'RaRight':  4.2667 }
  , { 'ConciseName':'معمل النحات', 'DecBottom':-40.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'قنطورس', 'DecBottom':-42.0000, 'RaLeft': 14.1667, 'RaRight': 14.9167 }
  , { 'ConciseName':'السبع', 'DecBottom':-42.0000, 'RaLeft': 15.6667, 'RaRight': 16.0000 }
  , { 'ConciseName':'العقرب', 'DecBottom':-42.0000, 'RaLeft': 16.0000, 'RaRight': 16.4208 }
  , { 'ConciseName':'آلة النقاش', 'DecBottom':-43.0000, 'RaLeft':  4.8333, 'RaRight':  5.0000 }
  , { 'ConciseName':'الحمامة', 'DecBottom':-43.0000, 'RaLeft':  5.0000, 'RaRight':  6.5833 }
  , { 'ConciseName':'الكوثل', 'DecBottom':-43.0000, 'RaLeft':  8.0000, 'RaRight':  8.3667 }
  , { 'ConciseName':'النهر', 'DecBottom':-44.0000, 'RaLeft':  3.4167, 'RaRight':  3.8667 }
  , { 'ConciseName':'العقرب', 'DecBottom':-45.5000, 'RaLeft': 16.4208, 'RaRight': 17.8333 }
  , { 'ConciseName':'الإكليل الجنوبي', 'DecBottom':-45.5000, 'RaLeft': 17.8333, 'RaRight': 19.1667 }
  , { 'ConciseName':'القوس', 'DecBottom':-45.5000, 'RaLeft': 19.1667, 'RaRight': 20.3333 }
  , { 'ConciseName':'المجهر', 'DecBottom':-45.5000, 'RaLeft': 20.3333, 'RaRight': 21.3333 }
  , { 'ConciseName':'النهر', 'DecBottom':-46.0000, 'RaLeft':  3.0000, 'RaRight':  3.4167 }
  , { 'ConciseName':'آلة النقاش', 'DecBottom':-46.5000, 'RaLeft':  4.5000, 'RaRight':  4.8333 }
  , { 'ConciseName':'السبع', 'DecBottom':-48.0000, 'RaLeft': 15.3333, 'RaRight': 15.6667 }
  , { 'ConciseName':'العنقاء', 'DecBottom':-48.1667, 'RaLeft':  0.0000, 'RaRight':  2.3333 }
  , { 'ConciseName':'النهر', 'DecBottom':-49.0000, 'RaLeft':  2.6667, 'RaRight':  3.0000 }
  , { 'ConciseName':'الساعة', 'DecBottom':-49.0000, 'RaLeft':  4.0833, 'RaRight':  4.2667 }
  , { 'ConciseName':'آلة النقاش', 'DecBottom':-49.0000, 'RaLeft':  4.2667, 'RaRight':  4.5000 }
  , { 'ConciseName':'الكركي', 'DecBottom':-50.0000, 'RaLeft': 21.3333, 'RaRight': 22.0000 }
  , { 'ConciseName':'الكوثل', 'DecBottom':-50.7500, 'RaLeft':  6.0000, 'RaRight':  8.0000 }
  , { 'ConciseName':'الشراع', 'DecBottom':-50.7500, 'RaLeft':  8.0000, 'RaRight':  8.1667 }
  , { 'ConciseName':'النهر', 'DecBottom':-51.0000, 'RaLeft':  2.4167, 'RaRight':  2.6667 }
  , { 'ConciseName':'الساعة', 'DecBottom':-51.0000, 'RaLeft':  3.8333, 'RaRight':  4.0833 }
  , { 'ConciseName':'العنقاء', 'DecBottom':-51.5000, 'RaLeft':  0.0000, 'RaRight':  1.8333 }
  , { 'ConciseName':'القاعدة', 'DecBottom':-52.5000, 'RaLeft':  6.0000, 'RaRight':  6.1667 }
  , { 'ConciseName':'الشراع', 'DecBottom':-53.0000, 'RaLeft':  8.1667, 'RaRight':  8.4500 }
  , { 'ConciseName':'الساعة', 'DecBottom':-53.1667, 'RaLeft':  3.5000, 'RaRight':  3.8333 }
  , { 'ConciseName':'أبو سيف', 'DecBottom':-53.1667, 'RaLeft':  3.8333, 'RaRight':  4.0000 }
  , { 'ConciseName':'العنقاء', 'DecBottom':-53.5000, 'RaLeft':  0.0000, 'RaRight':  1.5833 }
  , { 'ConciseName':'النهر', 'DecBottom':-54.0000, 'RaLeft':  2.1667, 'RaRight':  2.4167 }
  , { 'ConciseName':'آلة الرسام', 'DecBottom':-54.0000, 'RaLeft':  4.5000, 'RaRight':  5.0000 }
  , { 'ConciseName':'السبع', 'DecBottom':-54.0000, 'RaLeft': 15.0500, 'RaRight': 15.3333 }
  , { 'ConciseName':'الشراع', 'DecBottom':-54.5000, 'RaLeft':  8.4500, 'RaRight':  8.8333 }
  , { 'ConciseName':'القاعدة', 'DecBottom':-55.0000, 'RaLeft':  6.1667, 'RaRight':  6.5000 }
  , { 'ConciseName':'قنطورس', 'DecBottom':-55.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'السبع', 'DecBottom':-55.0000, 'RaLeft': 14.1667, 'RaRight': 15.0500 }
  , { 'ConciseName':'مربع النجار', 'DecBottom':-55.0000, 'RaLeft': 15.0500, 'RaRight': 15.3333 }
  , { 'ConciseName':'أبو سيف', 'DecBottom':-56.5000, 'RaLeft':  4.0000, 'RaRight':  4.3333 }
  , { 'ConciseName':'الشراع', 'DecBottom':-56.5000, 'RaLeft':  8.8333, 'RaRight': 11.0000 }
  , { 'ConciseName':'قنطورس', 'DecBottom':-56.5000, 'RaLeft': 11.0000, 'RaRight': 11.2500 }
  , { 'ConciseName':'المجمرة', 'DecBottom':-57.0000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'التلسكوب', 'DecBottom':-57.0000, 'RaLeft': 18.0000, 'RaRight': 20.3333 }
  , { 'ConciseName':'الكركي', 'DecBottom':-57.0000, 'RaLeft': 22.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'الساعة', 'DecBottom':-57.5000, 'RaLeft':  3.2000, 'RaRight':  3.5000 }
  , { 'ConciseName':'آلة الرسام', 'DecBottom':-57.5000, 'RaLeft':  5.0000, 'RaRight':  5.5000 }
  , { 'ConciseName':'القاعدة', 'DecBottom':-58.0000, 'RaLeft':  6.5000, 'RaRight':  6.8333 }
  , { 'ConciseName':'العنقاء', 'DecBottom':-58.5000, 'RaLeft':  0.0000, 'RaRight':  1.3333 }
  , { 'ConciseName':'النهر', 'DecBottom':-58.5000, 'RaLeft':  1.3333, 'RaRight':  2.1667 }
  , { 'ConciseName':'العنقاء', 'DecBottom':-58.5000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'أبو سيف', 'DecBottom':-59.0000, 'RaLeft':  4.3333, 'RaRight':  4.5833 }
  , { 'ConciseName':'مربع النجار', 'DecBottom':-60.0000, 'RaLeft': 15.3333, 'RaRight': 16.4208 }
  , { 'ConciseName':'الهندي', 'DecBottom':-60.0000, 'RaLeft': 20.3333, 'RaRight': 21.3333 }
  , { 'ConciseName':'آلة الرسام', 'DecBottom':-61.0000, 'RaLeft':  5.5000, 'RaRight':  6.0000 }
  , { 'ConciseName':'البيكار', 'DecBottom':-61.0000, 'RaLeft': 15.1667, 'RaRight': 15.3333 }
  , { 'ConciseName':'المجمرة', 'DecBottom':-61.0000, 'RaLeft': 16.4208, 'RaRight': 16.5833 }
  , { 'ConciseName':'البيكار', 'DecBottom':-63.5833, 'RaLeft': 14.9167, 'RaRight': 15.1667 }
  , { 'ConciseName':'المجمرة', 'DecBottom':-63.5833, 'RaLeft': 16.5833, 'RaRight': 16.7500 }
  , { 'ConciseName':'آلة الرسام', 'DecBottom':-64.0000, 'RaLeft':  6.0000, 'RaRight':  6.8333 }
  , { 'ConciseName':'القاعدة', 'DecBottom':-64.0000, 'RaLeft':  6.8333, 'RaRight':  9.0333 }
  , { 'ConciseName':'قنطورس', 'DecBottom':-64.0000, 'RaLeft': 11.2500, 'RaRight': 11.8333 }
  , { 'ConciseName':'الصليب الجنوبي', 'DecBottom':-64.0000, 'RaLeft': 11.8333, 'RaRight': 12.8333 }
  , { 'ConciseName':'قنطورس', 'DecBottom':-64.0000, 'RaLeft': 12.8333, 'RaRight': 14.5333 }
  , { 'ConciseName':'البيكار', 'DecBottom':-65.0000, 'RaLeft': 13.5000, 'RaRight': 13.6667 }
  , { 'ConciseName':'المجمرة', 'DecBottom':-65.0000, 'RaLeft': 16.7500, 'RaRight': 16.8333 }
  , { 'ConciseName':'الساعة', 'DecBottom':-67.5000, 'RaLeft':  2.1667, 'RaRight':  3.2000 }
  , { 'ConciseName':'الشبكة', 'DecBottom':-67.5000, 'RaLeft':  3.2000, 'RaRight':  4.5833 }
  , { 'ConciseName':'البيكار', 'DecBottom':-67.5000, 'RaLeft': 14.7500, 'RaRight': 14.9167 }
  , { 'ConciseName':'المجمرة', 'DecBottom':-67.5000, 'RaLeft': 16.8333, 'RaRight': 17.5000 }
  , { 'ConciseName':'الطاووس', 'DecBottom':-67.5000, 'RaLeft': 17.5000, 'RaRight': 18.0000 }
  , { 'ConciseName':'الطوقان', 'DecBottom':-67.5000, 'RaLeft': 22.0000, 'RaRight': 23.3333 }
  , { 'ConciseName':'أبو سيف', 'DecBottom':-70.0000, 'RaLeft':  4.5833, 'RaRight':  6.5833 }
  , { 'ConciseName':'البيكار', 'DecBottom':-70.0000, 'RaLeft': 13.6667, 'RaRight': 14.7500 }
  , { 'ConciseName':'المثلث الجنوبي', 'DecBottom':-70.0000, 'RaLeft': 14.7500, 'RaRight': 17.0000 }
  , { 'ConciseName':'الطوقان', 'DecBottom':-75.0000, 'RaLeft':  0.0000, 'RaRight':  1.3333 }
  , { 'ConciseName':'حية الماء', 'DecBottom':-75.0000, 'RaLeft':  3.5000, 'RaRight':  4.5833 }
  , { 'ConciseName':'السمكة الطائرة', 'DecBottom':-75.0000, 'RaLeft':  6.5833, 'RaRight':  9.0333 }
  , { 'ConciseName':'القاعدة', 'DecBottom':-75.0000, 'RaLeft':  9.0333, 'RaRight': 11.2500 }
  , { 'ConciseName':'الذبابة', 'DecBottom':-75.0000, 'RaLeft': 11.2500, 'RaRight': 13.6667 }
  , { 'ConciseName':'الطاووس', 'DecBottom':-75.0000, 'RaLeft': 18.0000, 'RaRight': 21.3333 }
  , { 'ConciseName':'الهندي', 'DecBottom':-75.0000, 'RaLeft': 21.3333, 'RaRight': 23.3333 }
  , { 'ConciseName':'الطوقان', 'DecBottom':-75.0000, 'RaLeft': 23.3333, 'RaRight': 24.0000 }
  , { 'ConciseName':'الطوقان', 'DecBottom':-76.0000, 'RaLeft':  0.7500, 'RaRight':  1.3333 }
  , { 'ConciseName':'حية الماء', 'DecBottom':-82.5000, 'RaLeft':  0.0000, 'RaRight':  3.5000 }
  , { 'ConciseName':'الحرباء', 'DecBottom':-82.5000, 'RaLeft':  7.6667, 'RaRight': 13.6667 }
  , { 'ConciseName':'طائر الفردوس', 'DecBottom':-82.5000, 'RaLeft': 13.6667, 'RaRight': 18.0000 }
  , { 'ConciseName':'الجبل', 'DecBottom':-85.0000, 'RaLeft':  3.5000, 'RaRight':  7.6667 }
  , { 'ConciseName':'آلة الثمن', 'DecBottom':-90.0000, 'RaLeft':  0.0000, 'RaRight': 24.0000 }
];

var ConstellationByConciseName = {
    'أندروميدا' : { 'FullName':'Andromeda'              , 'PossessiveName':'Andromedae'              }
  , 'مفرغة الهواء' : { 'FullName':'Antila'                 , 'PossessiveName':'Antliae'                 }
  , 'طائر الفردوس' : { 'FullName':'Apus'                   , 'PossessiveName':'Apodis'                  }
  , 'العقاب' : { 'FullName':'Aquila'                 , 'PossessiveName':'Aquilae'                 }
  , 'الدلو' : { 'FullName':'Aquarius'               , 'PossessiveName':'Aquarii'                 }
  , 'المجمرة' : { 'FullName':'Ara'                    , 'PossessiveName':'Arae'                    }
  , 'الحمل' : { 'FullName':'Aries'                  , 'PossessiveName':'Arietis'                 }
  , 'ممسك الأعنة' : { 'FullName':'Auriga'                 , 'PossessiveName':'Aurigae'                 }
  , 'العواء' : { 'FullName':'Bootes'                 , 'PossessiveName':'Bootis'                  }
  , 'آلة النقاش' : { 'FullName':'Caelum'                 , 'PossessiveName':'Caeli'                   }
  , 'الزرافة' : { 'FullName':'Camelopardis'           , 'PossessiveName':'Camelopardalis'          }
  , 'الجدي' : { 'FullName':'Capricornus'            , 'PossessiveName':'Capricorni'              }
  , 'القاعدة' : { 'FullName':'Carina'                 , 'PossessiveName':'Carinae'                 }
  , 'ذات الكرسي' : { 'FullName':'Cassiopeia'             , 'PossessiveName':'Cassiopeiae'             }
  , 'قنطورس' : { 'FullName':'Centaurus'              , 'PossessiveName':'Centauri'                }
  , 'Cep' : { 'FullName':'Cepheus'                , 'PossessiveName':'Cephei'                  }
  , 'قيطس' : { 'FullName':'Cetus'                  , 'PossessiveName':'Ceti'                    }
  , 'الحرباء' : { 'FullName':'Chamaeleon'             , 'PossessiveName':'Chamaeleontis'           }
  , 'البيكار' : { 'FullName':'Circinus'               , 'PossessiveName':'Circini'                 }
  , 'الكلب الأكبر' : { 'FullName':'Canis Major'            , 'PossessiveName':'Canis Majoris'           }
  , 'الكلب الأصغر' : { 'FullName':'Canis Minor'            , 'PossessiveName':'Canis Minoris'           }
  , 'السرطان' : { 'FullName':'Cancer'                 , 'PossessiveName':'Cancri'                  }
  , 'الحمامة' : { 'FullName':'Columba'                , 'PossessiveName':'Columbae'                }
  , 'الضفيرة' : { 'FullName':'Coma Berenices'         , 'PossessiveName':'Comae Berenices'         }
  , 'الإكليل الجنوبي' : { 'FullName':'Corona Australis'       , 'PossessiveName':'Coronae Austrinae'       }
  , 'الإكليل الشمالي' : { 'FullName':'Corona Borealis'        , 'PossessiveName':'Coronae Borealis'        }
  , 'الباطية' : { 'FullName':'Crater'                 , 'PossessiveName':'Crateris'                }
  , 'الصليب الجنوبي' : { 'FullName':'Crux'                   , 'PossessiveName':'Crucis'                  }
  , 'الغراب' : { 'FullName':'Corvus'                 , 'PossessiveName':'Corvi'                   }
  , 'CVn' : { 'FullName':'Canes Venatici'         , 'PossessiveName':'Canum Venaticorum'       }
  , 'الدجاجة' : { 'FullName':'Cygnus'                 , 'PossessiveName':'Cygni'                   }
  , 'الدلفين' : { 'FullName':'Delphinus'              , 'PossessiveName':'Delphini'                }
  , 'أبو سيف' : { 'FullName':'Dorado'                 , 'PossessiveName':'Doradus'                 }
  , 'التنين' : { 'FullName':'Draco'                  , 'PossessiveName':'Draconis'                }
  , 'قطعة الفرس' : { 'FullName':'Equuleus'               , 'PossessiveName':'Equulei'                 }
  , 'النهر' : { 'FullName':'Eridanus'               , 'PossessiveName':'Eridani'                 }
  , 'الكور' : { 'FullName':'Fornax'                 , 'PossessiveName':'Fornacis'                }
  , 'التوأمين' : { 'FullName':'Gemini'                 , 'PossessiveName':'Geminorum'               }
  , 'الكركي' : { 'FullName':'Grus'                   , 'PossessiveName':'Gruis'                   }
  , 'هرقل' : { 'FullName':'Hercules'               , 'PossessiveName':'Herculis'                }
  , 'الساعة' : { 'FullName':'Horologium'             , 'PossessiveName':'Horologii'               }
  , 'الشجاع' : { 'FullName':'Hydra'                  , 'PossessiveName':'Hydrae'                  }
  , 'حية الماء' : { 'FullName':'Hydrus'                 , 'PossessiveName':'Hydri'                   }
  , 'الهندي' : { 'FullName':'Indus'                  , 'PossessiveName':'Indi'                    }
  , 'العظاءة' : { 'FullName':'Lacerta'                , 'PossessiveName':'Lacertae'                }
  , 'الأسد' : { 'FullName':'Leo'                    , 'PossessiveName':'Leonis'                  }
  , 'الأرنب' : { 'FullName':'Lepus'                  , 'PossessiveName':'Leporis'                 }
  , 'الميزان' : { 'FullName':'Libra'                  , 'PossessiveName':'Librae'                  }
  , 'الأسد الأصغر' : { 'FullName':'Leo Minor'              , 'PossessiveName':'Leonis Minoris'          }
  , 'السبع' : { 'FullName':'Lupus'                  , 'PossessiveName':'Lupi'                    }
  , 'الوشق' : { 'FullName':'Lynx'                   , 'PossessiveName':'Lyncis'                  }
  , 'القيثارة' : { 'FullName':'Lyra'                   , 'PossessiveName':'Lyrae'                   }
  , 'الجبل' : { 'FullName':'Mensa'                  , 'PossessiveName':'Mensae'                  }
  , 'المجهر' : { 'FullName':'Microscopium'           , 'PossessiveName':'Microscopii'             }
  , 'وحيد القرن' : { 'FullName':'Monoceros'              , 'PossessiveName':'Monocerotis'             }
  , 'الذبابة' : { 'FullName':'Musca'                  , 'PossessiveName':'Muscae'                  }
  , 'مربع النجار' : { 'FullName':'Norma'                  , 'PossessiveName':'Normae'                  }
  , 'آلة الثمن' : { 'FullName':'Octans'                 , 'PossessiveName':'Octantis'                }
  , 'الحواء' : { 'FullName':'Ophiuchus'              , 'PossessiveName':'Ophiuchi'                }
  , 'الجبار' : { 'FullName':'Orion'                  , 'PossessiveName':'Orionis'                 }
  , 'الطاووس' : { 'FullName':'Pavo'                   , 'PossessiveName':'Pavonis'                 }
  , 'الفرس المجنح' : { 'FullName':'Pegasus'                , 'PossessiveName':'Pegasi'                  }
  , 'برشاوس' : { 'FullName':'Perseus'                , 'PossessiveName':'Persei'                  }
  , 'العنقاء' : { 'FullName':'Phoenix'                , 'PossessiveName':'Phoenicis'               }
  , 'آلة الرسام' : { 'FullName':'Pictor'                 , 'PossessiveName':'Pictoris'                }
  , 'الحوت الجنوبي' : { 'FullName':'Pisces Austrinus'       , 'PossessiveName':'Piscis Austrini'         }
  , 'الحوت' : { 'FullName':'Pisces'                 , 'PossessiveName':'Piscium'                 }
  , 'الكوثل' : { 'FullName':'Puppis'                 , 'PossessiveName':'Puppis'                  }
  , 'بيت الإبرة' : { 'FullName':'Pyxis'                  , 'PossessiveName':'Pyxidis'                 }
  , 'الشبكة' : { 'FullName':'Reticulum'              , 'PossessiveName':'Reticuli'                }
  , 'معمل النحات' : { 'FullName':'Sculptor'               , 'PossessiveName':'Sculptoris'              }
  , 'العقرب' : { 'FullName':'Scorpius'               , 'PossessiveName':'Scorpii'                 }
  , 'الترس' : { 'FullName':'Scutum'                 , 'PossessiveName':'Scuti'                   }
  , 'الحية' : { 'FullName':'Serpens'                , 'PossessiveName':'Serpentis'               }
  , 'آلة السدس' : { 'FullName':'Sextans'                , 'PossessiveName':'Sextantis'               }
  , 'السهم' : { 'FullName':'Sagitta'                , 'PossessiveName':'Sagittae'                }
  , 'القوس' : { 'FullName':'Sagittarius'            , 'PossessiveName':'Sagittarii'              }
  , 'الثور' : { 'FullName':'Taurus'                 , 'PossessiveName':'Tauri'                   }
  , 'التلسكوب' : { 'FullName':'Telescopium'            , 'PossessiveName':'Telescopii'              }
  , 'المثلث الجنوبي' : { 'FullName':'Triangulum Australe'    , 'PossessiveName':'Trianguli Australis'     }
  , 'المثلث' : { 'FullName':'Triangulum'             , 'PossessiveName':'Trianguli'               }
  , 'الطوقان' : { 'FullName':'Tucana'                 , 'PossessiveName':'Tucana'                  }
  , 'الدب الأكبر' : { 'FullName':'Ursa Major'             , 'PossessiveName':'Ursae Majoris'           }
  , 'الدب الأصغر' : { 'FullName':'Ursa Minor'             , 'PossessiveName':'Ursae Minoris'           }
  , 'الشراع' : { 'FullName':'Vela'                   , 'PossessiveName':'Velorum'                 }
  , 'العذراء' : { 'FullName':'Virgo'                  , 'PossessiveName':'Virginis'                }
  , 'السمكة الطائرة' : { 'FullName':'Volans'                 , 'PossessiveName':'Volantis'                }
  , 'الثعلب' : { 'FullName':'Vulpecula'              , 'PossessiveName':'Vulpeculae'              }
};

// end of file  constellation.js